package ru.vka.upo.ui;

import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import ru.vka.upo.model.Settings;
import ru.vka.upo.model.VariantTable;

/**
 * Экран приветствия: краткое описание работы и порядка её выполнения.
 */
public class WelcomePanel extends javax.swing.JPanel {

    private final MainFrame owner;

    public WelcomePanel(MainFrame owner) {
        this.owner = owner;
        initComponents();
        customize();
    }

    private void customize() {
        txtWelcome.setFont(new Font(Font.SERIF, Font.PLAIN, 15));
        txtWelcome.setOpaque(false);
        txtWelcome.setText(buildText());
        txtWelcome.setCaretPosition(0);
        lblVariantValue.setFont(lblVariantValue.getFont().deriveFont(Font.BOLD));
    }

    /**
     * Текст пункта 1 описания зависит от настройки test.enabled: если
     * входной контроль отключён, шаг с ним из порядка выполнения убирается,
     * а последующие пункты не перенумеровываются заново – важен их порядок,
     * а не сквозная нумерация.
     */
    private String buildText() {
        String step1 = Settings.testEnabled()
                ? "1. Входной контроль знаний. Предлагается пять вопросов по теории "
                + "работы, за каждый правильный ответ начисляется один балл. "
                + "К выполнению работы допускаются обучающиеся, набравшие не менее "
                + "трёх баллов.\n\n"
                : "Входной контроль знаний отключён настройкой программы – работа "
                + "начинается сразу с ввода исходных данных.\n\n";
        return TEXT_HEAD + step1 + TEXT_TAIL;
    }

    /**
     * Вызывается при каждом показе экрана: сведения о вошедшем к этому
     * времени уже приняты, и назначенный вариант можно показать.
     */
    public void onShown() {
        VariantTable.Variant v = owner.getSelectedVariant();
        lblVariantValue.setText(v == null ? "не назначен" : v.toString());
        btnStart.setEnabled(v != null);
        btnStart.setText(Settings.testEnabled()
                ? "Начать входной контроль" : "Начать выполнение работы");
    }

    private static final String TEXT_HEAD =
            "Лабораторная работа\n"
            + "«Исследование эффективности устройств предварительной обработки "
            + "радионавигационных систем»\n"
            + "\n"
            + "Цель работы: изучить методы предварительной обработки, основанные на "
            + "полиномиальном усреднении результатов измерения текущих навигационных "
            + "параметров, и исследовать точностные характеристики этих методов "
            + "на модели процесса обработки.\n"
            + "\n"
            + "Порядок выполнения:\n"
            + "\n";

    private static final String TEXT_TAIL =
            "2. Ввод исходных данных: параметры траектории и условий измерений "
            + "(признак траектории, измеряемые параметры, интервал измерений, "
            + "высота орбиты, расстояние до трассы, СКО измерений) и параметры режима "
            + "обработки (степень аппроксимирующего полинома, объём выборки, шаг "
            + "измерений, момент привязки оценки).\n"
            + "\n"
            + "3. Расчёт ошибок оценивания: динамической, случайной и полной средней "
            + "квадратической, раздельно по дальности и радиальной скорости.\n"
            + "\n"
            + "4. Исследование зависимости ошибок от параметров режима обработки. "
            + "По каждому пункту задания обучающийся сам задаёт режимы, снимает "
            + "результаты и заносит их в рабочую тетрадь. Готовых зависимостей "
            + "программа не показывает: график строится по тем числам, которые "
            + "обучающийся выписал сам, и по нему делается вывод об оптимальном "
            + "режиме обработки.\n"
            + "\n"
            + "5. Иллюстрации, открытые всё время работы: геометрия пролёта, "
            + "истинный ход измеряемого параметра, результаты измерений с шумом "
            + "и аппроксимирующая кривая. Отдельно даётся справка о том, как "
            + "работает метод наименьших квадратов.\n"
            + "\n"
            + "6. Отчёт по работе программа собирает сама: шапка с фамилией, "
            + "группой и вариантом, исходные данные, заполненные таблицы, "
            + "графики и выводы обучающегося.\n"
            + "\n"
            + "Кафедра космической радиолокации и радионавигации.";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrWelcome = new javax.swing.JScrollPane();
        txtWelcome = new javax.swing.JTextArea();
        lblVariant = new javax.swing.JLabel();
        lblVariantValue = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        txtWelcome.setEditable(false);
        txtWelcome.setLineWrap(true);
        txtWelcome.setWrapStyleWord(true);
        txtWelcome.setColumns(20);
        txtWelcome.setRows(5);
        scrWelcome.setViewportView(txtWelcome);

        lblVariant.setText("Ваш вариант");

        lblVariantValue.setText("не назначен");

        btnLogin.setText("Изменить свои данные");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnStart.setText("Начать входной контроль");
        btnStart.setEnabled(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVariantValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVariant)
                    .addComponent(lblVariantValue)
                    .addComponent(btnLogin)
                    .addComponent(btnStart))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (owner.getSelectedVariant() == null) {
            owner.setStatus("Вариант не назначен: вернитесь к вводу своих данных.");
            return;
        }
        if (Settings.testEnabled()) {
            owner.showCard(MainFrame.CARD_TEST);
        } else {
            // входной контроль отключён настройкой test.enabled – экран
            // контроля пропускается, оценка в отчёте не появится
            owner.showCard(MainFrame.CARD_INPUT);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        owner.showCard(MainFrame.CARD_LOGIN);
    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblVariant;
    private javax.swing.JLabel lblVariantValue;
    private javax.swing.JScrollPane scrWelcome;
    private javax.swing.JTextArea txtWelcome;
    // End of variables declaration//GEN-END:variables
}
